In [1]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import time

In [2]:
# Import the census data into a pandas DataFrame
census_AIAN_2000_pd = pd.read_csv("census_data/AIAN/2000_AIAN_cleaned .csv")

# Preview the data
census_AIAN_2000_pd

,CountyID,CountyName,TotalPopulation,"Less than $10,000","$10,000 to $14,999","$15,000 to $19,999","$20,000 to $24,999","$25,000 to $29,999","$30,000 to $34,999","$35,000 to $39,999",...,"$45,000 to $49,999","$50,000 to $59,999","$60,000 to $74,999","$75,000 to $99,999","$100,000 to $124,999","$125,000 to $149,999","$150,000 to $199,999","$200,000 or more",Year,Race
0,2020,"Anchorage Municipality, Alaska",8091,837,939,363,222,748,585,475,...,405,632,954,346,489,492,58,408,2000,AIAN
1,4001,"Apache County, Arizona",12081,3130,1404,794,1152,553,790,476,...,303,890,620,780,166,176,35,25,2000,AIAN
2,4005,"Coconino County, Arizona",8367,1183,405,473,1000,847,557,872,...,439,670,393,606,187,46,159,0,2000,AIAN
3,4013,"Maricopa County, Arizona",20744,2536,947,1460,2111,1323,2227,1938,...,435,2307,1837,1945,457,244,104,55,2000,AIAN
4,4017,"Navajo County, Arizona",13271,3975,1255,707,1498,748,1117,412,...,336,822,1021,337,224,163,223,79,2000,AIAN
5,4019,"Pima County, Arizona",10882,2486,621,860,906,688,665,534,...,809,363,926,826,247,119,168,0,2000,AIAN
6,6037,"Los Angeles County, California",14517,1544,1509,727,955,562,576,656,...,513,1168,1642,1397,1002,482,766,212,2000,AIAN
7,6059,"Orange County, California",3981,273,584,209,99,152,90,337,...,0,145,453,860,405,0,45,267,2000,AIAN
8,6065,"Riverside County, California",6481,711,551,100,397,56,590,97,...,186,569,625,1024,785,123,134,309,2000,AIAN
9,6067,"Sacramento County, California",5239,146,672,341,420,19,175,270,...,207,363,762,333,406,0,452,201,2000,AIAN
10,6071,"San Bernardino County, California",6279,507,271,483,174,485,491,521,...,482,398,707,415,353,335,227,0,2000,AIAN
11,6073,"San Diego County, California",5883,536,450,503,561,245,190,506,...,101,474,480,668,616,126,267,30,2000,AIAN
12,17031,"Cook County, Illinois",4494,888,272,128,226,117,453,206,...,209,183,858,400,281,96,0,0,2000,AIAN
13,35001,"Bernalillo County, New Mexico",9482,931,396,629,780,441,427,591,...,546,1307,963,1201,381,257,116,0,2000,AIAN
14,35031,"McKinley County, New Mexico",11498,2567,1248,1198,1323,896,753,397,...,604,566,623,538,159,0,79,33,2000,AIAN
15,35043,"Sandoval County, New Mexico",4427,531,182,114,154,336,530,431,...,386,192,367,317,288,0,87,0,2000,AIAN
16,35045,"San Juan County, New Mexico",12390,2354,987,1173,562,976,539,331,...,438,1587,704,1509,553,233,22,87,2000,AIAN
17,37155,"Robeson County, North Carolina",15110,2285,1485,1625,1258,1440,1710,1019,...,751,366,749,642,99,365,0,109,2000,AIAN
18,40027,"Cleveland County, Oklahoma",3207,611,0,92,228,27,132,136,...,174,245,601,353,123,34,143,86,2000,AIAN
19,40109,"Oklahoma County, Oklahoma",7657,1227,341,266,585,748,573,714,...,309,388,924,684,490,138,0,43,2000,AIAN
20,40131,"Rogers County, Oklahoma",4334,259,449,456,356,177,228,217,...,81,438,621,217,95,0,171,115,2000,AIAN
21,40143,"Tulsa County, Oklahoma",10076,996,991,654,391,891,537,981,...,402,655,503,1179,511,452,247,172,2000,AIAN
22,48029,"Bexar County, Texas",5671,324,803,111,607,52,423,147,...,530,370,460,762,141,478,47,0,2000,AIAN
23,48201,"Harris County, Texas",5956,752,765,342,133,722,197,385,...,345,121,532,477,483,89,100,159,2000,AIAN
24,53033,"King County, Washington",5444,951,122,528,512,422,119,170,...,95,147,588,433,527,165,324,0,2000,AIAN

In [3]:
census_AIAN_2005_pd = pd.read_csv("census_data/AIAN/2005_AIAN_cleaned .csv")
census_AIAN_2005_pd

,CountyID,CountyName,TotalPopulation,"Less than $10,000","$10,000 to $14,999","$15,000 to $19,999","$20,000 to $24,999","$25,000 to $29,999","$30,000 to $34,999","$35,000 to $39,999",...,"$45,000 to $49,999","$50,000 to $59,999","$60,000 to $74,999","$75,000 to $99,999","$100,000 to $124,999","$125,000 to $149,999","$150,000 to $199,999","$200,000 or more",Year,Race
0,2020,"Anchorage Municipality, Alaska",5170,688,187,211,196,91,307,404,...,92,577,332,551,738,259,243,43,2005,AIAN
1,4001,"Apache County, Arizona",13343,4506,1625,670,746,1059,948,865,...,66,831,708,673,72,15,0,72,2005,AIAN
2,4005,"Coconino County, Arizona",8975,1771,651,944,607,630,419,651,...,401,836,834,602,357,0,73,0,2005,AIAN
3,4013,"Maricopa County, Arizona",20043,2270,2522,1570,1360,1670,1599,1077,...,649,1176,1771,1835,808,446,133,0,2005,AIAN
4,4017,"Navajo County, Arizona",12953,3664,936,1001,1331,1179,1350,797,...,269,582,478,367,147,131,0,0,2005,AIAN
5,4019,"Pima County, Arizona",8473,1677,725,579,578,383,672,585,...,309,360,1025,270,152,217,89,0,2005,AIAN
6,6037,"Los Angeles County, California",16970,1285,688,1045,836,831,1182,546,...,363,1204,1919,2883,967,587,566,903,2005,AIAN
7,6065,"Riverside County, California",5493,502,358,562,162,625,247,79,...,200,415,710,468,366,332,73,224,2005,AIAN
8,6067,"Sacramento County, California",6673,247,473,301,0,71,762,382,...,470,569,1036,1168,107,367,0,178,2005,AIAN
9,6071,"San Bernardino County, California",6347,523,402,240,538,104,318,258,...,334,986,1165,680,300,160,46,35,2005,AIAN
10,6073,"San Diego County, California",7305,450,496,698,395,401,287,399,...,357,515,406,839,821,349,419,192,2005,AIAN
11,26163,"Wayne County, Michigan",3002,423,164,480,200,133,0,599,...,85,104,392,197,93,0,132,0,2005,AIAN
12,35001,"Bernalillo County, New Mexico",10033,1032,2165,113,1479,640,477,543,...,98,836,565,1073,120,54,153,0,2005,AIAN
13,35031,"McKinley County, New Mexico",13663,3333,1385,1354,1467,1104,1108,653,...,369,755,550,681,284,166,61,0,2005,AIAN
14,35043,"Sandoval County, New Mexico",3535,558,142,451,762,344,100,102,...,247,110,151,430,102,0,0,0,2005,AIAN
15,35045,"San Juan County, New Mexico",12585,2004,1492,1494,543,1424,1047,765,...,484,373,712,930,189,114,125,113,2005,AIAN
16,37155,"Robeson County, North Carolina",16788,2202,3168,1692,1221,1405,566,1916,...,595,640,1313,792,204,65,44,42,2005,AIAN
17,40101,"Muskogee County, Oklahoma",2941,223,156,235,528,139,242,132,...,46,179,487,418,0,0,0,0,2005,AIAN
18,40109,"Oklahoma County, Oklahoma",8459,939,984,398,495,478,866,422,...,558,578,885,624,219,44,102,212,2005,AIAN
19,40143,"Tulsa County, Oklahoma",11245,1165,740,690,992,967,294,621,...,136,1206,1481,1065,499,115,177,122,2005,AIAN
20,48201,"Harris County, Texas",5127,236,434,259,126,407,458,457,...,152,210,978,0,623,213,113,211,2005,AIAN
21,53033,"King County, Washington",6137,1040,692,187,232,508,142,495,...,245,430,763,336,158,58,0,64,2005,AIAN

In [5]:
census_AIAN_2008_pd = pd.read_csv("census_data/AIAN/2008_AIAN_cleaned.csv")

# Preview the data
census_AIAN_2008_pd

,CountyID,CountyName,TotalPopulation,"Less than $10,000","$10,000 to $14,999","$15,000 to $19,999","$20,000 to $24,999","$25,000 to $29,999","$30,000 to $34,999","$35,000 to $39,999",...,"$45,000 to $49,999","$50,000 to $59,999","$60,000 to $74,999","$75,000 to $99,999","$100,000 to $124,999","$125,000 to $149,999","$150,000 to $199,999","$200,000 or more",Year,Race
0,2020,"Anchorage Municipality, Alaska",4764,173,351,304,183,155,634,399,...,222,399,273,772,168,224,36,212,2008,AIAN
1,4001,"Apache County, Arizona",10602,3243,886,718,721,486,462,677,...,519,614,554,639,280,182,48,0,2008,AIAN
2,4005,"Coconino County, Arizona",9610,1492,586,611,552,276,1133,348,...,353,894,738,1360,404,180,0,0,2008,AIAN
3,4013,"Maricopa County, Arizona",19568,2415,967,1081,1595,827,1228,1328,...,418,1206,2255,3098,1030,502,301,151,2008,AIAN
4,4017,"Navajo County, Arizona",13498,2248,851,1159,990,985,844,1114,...,485,903,823,937,530,159,290,150,2008,AIAN
5,4019,"Pima County, Arizona",8553,1135,399,473,716,1157,693,671,...,424,657,818,642,196,134,35,42,2008,AIAN
6,6037,"Los Angeles County, California",17773,893,981,659,786,563,1152,1168,...,738,1961,1742,2801,1691,878,547,561,2008,AIAN
7,6059,"Orange County, California",5029,0,334,303,241,102,223,141,...,329,291,583,1081,249,489,210,231,2008,AIAN
8,6065,"Riverside County, California",7445,647,467,359,591,150,568,426,...,579,383,926,1032,323,370,76,458,2008,AIAN
9,6067,"Sacramento County, California",4564,208,355,324,321,483,516,121,...,223,305,338,632,402,79,116,0,2008,AIAN
10,6071,"San Bernardino County, California",7950,504,208,440,323,512,197,741,...,981,1150,700,409,925,262,73,244,2008,AIAN
11,6073,"San Diego County, California",8861,860,771,495,438,288,703,182,...,642,674,840,857,391,643,221,297,2008,AIAN
12,17031,"Cook County, Illinois",4450,289,247,49,384,218,245,29,...,64,488,1071,555,242,103,260,0,2008,AIAN
13,35001,"Bernalillo County, New Mexico",9891,938,727,1136,884,535,204,677,...,195,1345,621,1090,660,297,137,40,2008,AIAN
14,35031,"McKinley County, New Mexico",11952,2396,867,1247,950,1100,943,468,...,427,836,836,922,405,60,0,0,2008,AIAN
15,35043,"Sandoval County, New Mexico",4040,388,371,456,149,385,184,102,...,203,521,518,127,259,131,0,0,2008,AIAN
16,35045,"San Juan County, New Mexico",10896,1418,906,455,824,103,724,505,...,645,836,970,1587,892,151,102,196,2008,AIAN
17,37155,"Robeson County, North Carolina",15038,2223,1450,1667,933,1363,904,1128,...,472,1395,1749,658,555,107,62,0,2008,AIAN
18,40101,"Muskogee County, Oklahoma",2900,333,273,630,125,49,285,119,...,279,124,164,173,109,168,11,0,2008,AIAN
19,40109,"Oklahoma County, Oklahoma",6240,558,394,267,596,252,272,477,...,303,652,533,1036,114,412,38,122,2008,AIAN
20,40143,"Tulsa County, Oklahoma",7104,442,251,393,623,381,410,884,...,329,405,753,815,456,250,69,63,2008,AIAN
21,48113,"Dallas County, Texas",3621,212,96,453,145,147,230,314,...,53,244,380,391,327,83,137,236,2008,AIAN
22,48201,"Harris County, Texas",6668,553,558,0,703,258,233,0,...,316,793,1126,346,283,69,185,756,2008,AIAN
23,48439,"Tarrant County, Texas",3282,265,185,156,0,112,255,350,...,164,426,226,390,188,156,128,79,2008,AIAN
24,53033,"King County, Washington",5473,280,0,260,436,697,293,511,...,287,453,238,520,671,95,168,374,2008,AIAN
25,53053,"Pierce County, Washington",3336,316,0,122,73,151,190,289,...,146,405,339,429,238,166,63,54,2008,AIAN

In [6]:
# Import the census data into a pandas DataFrame
census_AIAN_2010_pd = pd.read_csv("census_data/AIAN/2010_AIAN_cleaned.csv")

# Preview the data
census_AIAN_2010_pd.head()

,CountyID,CountyName,TotalPopulation,"Less than $10,000","$10,000 to $14,999","$15,000 to $19,999","$20,000 to $24,999","$25,000 to $29,999","$30,000 to $34,999","$35,000 to $39,999",...,"$45,000 to $49,999","$50,000 to $59,999","$60,000 to $74,999","$75,000 to $99,999","$100,000 to $124,999","$125,000 to $149,999","$150,000 to $199,999","$200,000 or more",Year,Race
0,2020,"Anchorage Municipality, Alaska",8091,837,939,363,222,748,585,475,...,405,632,954,346,489,492,58,408,2010,AIAN
1,4001,"Apache County, Arizona",12081,3130,1404,794,1152,553,790,476,...,303,890,620,780,166,176,35,25,2010,AIAN
2,4005,"Coconino County, Arizona",8367,1183,405,473,1000,847,557,872,...,439,670,393,606,187,46,159,0,2010,AIAN
3,4013,"Maricopa County, Arizona",20744,2536,947,1460,2111,1323,2227,1938,...,435,2307,1837,1945,457,244,104,55,2010,AIAN
4,4017,"Navajo County, Arizona",13271,3975,1255,707,1498,748,1117,412,...,336,822,1021,337,224,163,223,79,2010,AIAN

In [7]:
# Import the census data into a pandas DataFrame
census_AIAN_2013_pd = pd.read_csv("census_data/AIAN/2013_AIAN_cleaned .csv")

# Preview the data
census_AIAN_2013_pd.head()

,CountyID,CountyName,TotalPopulation,"Less than $10,000","$10,000 to $14,999","$15,000 to $19,999","$20,000 to $24,999","$25,000 to $29,999","$30,000 to $34,999","$35,000 to $39,999",...,"$45,000 to $49,999","$50,000 to $59,999","$60,000 to $74,999","$75,000 to $99,999","$100,000 to $124,999","$125,000 to $149,999","$150,000 to $199,999","$200,000 or more",Year,Race
0,2020,"Anchorage Municipality, Alaska",6669,540,187,693,386,214,471,250,...,356,274,509,830,532,431,184,138,2013,AIAN
1,4001,"Apache County, Arizona",11382,3126,1288,811,1057,590,802,528,...,182,968,726,484,223,161,60,26,2013,AIAN
2,4005,"Coconino County, Arizona",9899,1574,667,1160,408,441,594,512,...,458,830,647,1394,277,356,208,7,2013,AIAN
3,4013,"Maricopa County, Arizona",20703,2842,1246,852,1566,1600,1035,712,...,858,1889,1747,2676,1681,403,231,165,2013,AIAN
4,4017,"Navajo County, Arizona",11588,2887,928,846,884,1024,558,760,...,372,734,857,650,328,51,88,86,2013,AIAN

In [8]:
# Import the census data into a pandas DataFrame
census_AIAN_2016_pd = pd.read_csv("census_data/AIAN/2106_AIAN_cleaned.csv")

# Preview the data
census_AIAN_2016_pd.head()

,CountyID,CountyName,TotalPopulation,"Less than $10,000","$10,000 to $14,999","$15,000 to $19,999","$20,000 to $24,999","$25,000 to $29,999","$30,000 to $34,999","$35,000 to $39,999",...,"$45,000 to $49,999","$50,000 to $59,999","$60,000 to $74,999","$75,000 to $99,999","$100,000 to $124,999","$125,000 to $149,999","$150,000 to $199,999","$200,000 or more",Year,Race
0,2020,"Anchorage Municipality, Alaska",6899,304,457,425,436,530,301,110,...,173,716,531,1162,398,408,334,236,2016,AIAN
1,4001,"Apache County, Arizona",13752,3922,1380,1083,803,759,747,575,...,552,772,770,1012,635,207,27,53,2016,AIAN
2,4005,"Coconino County, Arizona",9353,1626,615,437,696,501,441,301,...,331,583,658,1681,395,309,243,58,2016,AIAN
3,4013,"Maricopa County, Arizona",22961,1921,769,730,1098,1767,1849,1075,...,1375,1741,2121,3332,1184,615,1518,418,2016,AIAN
4,4017,"Navajo County, Arizona",12074,3403,1005,996,890,819,717,545,...,434,451,650,864,512,171,75,100,2016,AIAN

In [10]:
census_AIAN_total_pd=pd.concat([census_AIAN_2000_pd,census_AIAN_2005_pd,census_AIAN_2008_pd, census_AIAN_2010_pd, census_AIAN_2013_pd, census_AIAN_2016_pd],ignore_index=True,
            )
census_AIAN_total_pd

,CountyID,CountyName,TotalPopulation,"Less than $10,000","$10,000 to $14,999","$15,000 to $19,999","$20,000 to $24,999","$25,000 to $29,999","$30,000 to $34,999","$35,000 to $39,999",...,"$45,000 to $49,999","$50,000 to $59,999","$60,000 to $74,999","$75,000 to $99,999","$100,000 to $124,999","$125,000 to $149,999","$150,000 to $199,999","$200,000 or more",Year,Race
0,2020,"Anchorage Municipality, Alaska",8091,837,939,363,222,748,585,475,...,405,632,954,346,489,492,58,408,2000,AIAN
1,4001,"Apache County, Arizona",12081,3130,1404,794,1152,553,790,476,...,303,890,620,780,166,176,35,25,2000,AIAN
2,4005,"Coconino County, Arizona",8367,1183,405,473,1000,847,557,872,...,439,670,393,606,187,46,159,0,2000,AIAN
3,4013,"Maricopa County, Arizona",20744,2536,947,1460,2111,1323,2227,1938,...,435,2307,1837,1945,457,244,104,55,2000,AIAN
4,4017,"Navajo County, Arizona",13271,3975,1255,707,1498,748,1117,412,...,336,822,1021,337,224,163,223,79,2000,AIAN
5,4019,"Pima County, Arizona",10882,2486,621,860,906,688,665,534,...,809,363,926,826,247,119,168,0,2000,AIAN
6,6037,"Los Angeles County, California",14517,1544,1509,727,955,562,576,656,...,513,1168,1642,1397,1002,482,766,212,2000,AIAN
7,6059,"Orange County, California",3981,273,584,209,99,152,90,337,...,0,145,453,860,405,0,45,267,2000,AIAN
8,6065,"Riverside County, California",6481,711,551,100,397,56,590,97,...,186,569,625,1024,785,123,134,309,2000,AIAN
9,6067,"Sacramento County, California",5239,146,672,341,420,19,175,270,...,207,363,762,333,406,0,452,201,2000,AIAN
10,6071,"San Bernardino County, California",6279,507,271,483,174,485,491,521,...,482,398,707,415,353,335,227,0,2000,AIAN
11,6073,"San Diego County, California",5883,536,450,503,561,245,190,506,...,101,474,480,668,616,126,267,30,2000,AIAN
12,17031,"Cook County, Illinois",4494,888,272,128,226,117,453,206,...,209,183,858,400,281,96,0,0,2000,AIAN
13,35001,"Bernalillo County, New Mexico",9482,931,396,629,780,441,427,591,...,546,1307,963,1201,381,257,116,0,2000,AIAN
14,35031,"McKinley County, New Mexico",11498,2567,1248,1198,1323,896,753,397,...,604,566,623,538,159,0,79,33,2000,AIAN
15,35043,"Sandoval County, New Mexico",4427,531,182,114,154,336,530,431,...,386,192,367,317,288,0,87,0,2000,AIAN
16,35045,"San Juan County, New Mexico",12390,2354,987,1173,562,976,539,331,...,438,1587,704,1509,553,233,22,87,2000,AIAN
17,37155,"Robeson County, North Carolina",15110,2285,1485,1625,1258,1440,1710,1019,...,751,366,749,642,99,365,0,109,2000,AIAN
18,40027,"Cleveland County, Oklahoma",3207,611,0,92,228,27,132,136,...,174,245,601,353,123,34,143,86,2000,AIAN
19,40109,"Oklahoma County, Oklahoma",7657,1227,341,266,585,748,573,714,...,309,388,924,684,490,138,0,43,2000,AIAN
20,40131,"Rogers County, Oklahoma",4334,259,449,456,356,177,228,217,...,81,438,621,217,95,0,171,115,2000,AIAN
21,40143,"Tulsa County, Oklahoma",10076,996,991,654,391,891,537,981,...,402,655,503,1179,511,452,247,172,2000,AIAN
22,48029,"Bexar County, Texas",5671,324,803,111,607,52,423,147,...,530,370,460,762,141,478,47,0,2000,AIAN
23,48201,"Harris County, Texas",5956,752,765,342,133,722,197,385,...,345,121,532,477,483,89,100,159,2000,AIAN
24,53033,"King County, Washington",5444,951,122,528,512,422,119,170,...,95,147,588,433,527,165,324,0,2000,AIAN
25,2020,"Anchorage Municipality, Alaska",5170,688,187,211,196,91,307,404,...,92,577,332,551,738,259,243,43,2005,AIAN
26,4001,"Apache County, Arizona",13343,4506,1625,670,746,1059,948,865,...,66,831,708,673,72,15,0,72,2005,AIAN
27,4005,"Coconino County, Arizona",8975,1771,651,944,607,630,419,651,...,401,836,834,602,357,0,73,0,2005,AIAN
28,4013,"Maricopa County, Arizona",20043,2270,2522,1570,1360,1670,1599,1077,...,649,1176,1771,1835,808,446,133,0,2005,AIAN
29,4017,"Navajo County, Arizona",12953,3664,936,1001,1331,1179,1350,797,...,269,582,478,367,147,131,0,0,2005,AIAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,4005,"Coconino County, Arizona",9353,1626,615,437,696,501,441,301,...,331,583,658,1681,395,309,243,58,2016,AIAN
134,4013,"Maricopa County, Arizona",22961,1921,769,730,1098,1767,1849,1075,...,1375,1741,2121,3332,1184,615,1518,418,2016,AIAN
135,4017,"Navajo County, Arizona",12074,3403,1005,996,890,819,717,545,...,434,451,650,864,512,171,75,100,2016,AIAN
136,4019,"Pima County, Arizona",9921,1418,673,954,955,571,615,739,...,285,509,753,900,347,101,75,164,2016,AIAN
137,4021,"Pinal County, Arizona",4768,923,552,307,375,287,0,735,...,127,119,379,476,212,14,25,85,2016,AIAN
138,6019,"Fresno County, California",3453,223,390,480,333,147,127,221,...,12,304,198,509,61,54,93,0,2016,AIAN
139,6037,"Los Angeles County, California",20578,1267,1292,1856,1215,1007,1280,984,...,877,1634,1927,1762,1407,860,1538,557,2016,AIAN
140,6065,"Riverside County, California",4983,488,503,16,297,137,104,143,...,355,544,266,182,313,305,345,250,2016,AIAN
141,6071,"San Bernardino County, California",5379,619,296,130,321,110,335,186,...,105,309,710,781,358,153,364,249,2016,AIAN
142,6073,"San Diego County, California",7096,592,258,594,956,379,180,227,...,149,698,507,484,734,264,548,217,2016,AIAN
143,17031,"Cook County, Illinois",4784,175,262,468,203,217,547,614,...,146,382,542,384,371,66,282,98,2016,AIAN
144,32003,"Clark County, Nevada",4843,489,103,514,652,448,380,258,...,196,216,320,471,250,218,7,95,2016,AIAN
145,35001,"Bernalillo County, New Mexico",11786,1482,796,1425,730,1191,638,437,...,164,993,825,1144,687,16,131,373,2016,AIAN
146,35031,"McKinley County, New Mexico",13629,2587,1527,1594,678,1057,843,618,...,308,903,901,1135,351,309,87,30,2016,AIAN
147,35043,"Sandoval County, New Mexico",4055,595,281,259,183,98,121,179,...,197,325,472,573,173,87,293,109,2016,AIAN
148,35045,"San Juan County, New Mexico",13423,1726,913,1093,679,1063,507,444,...,626,970,1037,2216,918,104,344,78,2016,AIAN
149,35049,"Santa Fe County, New Mexico",1802,209,8,57,177,51,256,55,...,91,103,131,467,101,0,45,16,2016,AIAN
150,37155,"Robeson County, North Carolina",17840,3034,1373,1618,1303,1131,854,947,...,709,991,1810,1606,782,208,206,317,2016,AIAN
151,40037,"Creek County, Oklahoma",2347,286,285,251,110,49,308,92,...,21,101,325,253,114,19,23,0,2016,AIAN
152,40101,"Muskogee County, Oklahoma",4071,277,263,385,133,435,274,142,...,76,412,274,575,284,23,112,97,2016,AIAN
153,40109,"Oklahoma County, Oklahoma",9437,1026,549,713,262,706,812,533,...,436,916,1057,679,536,233,370,274,2016,AIAN
154,40125,"Pottawatomie County, Oklahoma",2804,408,255,169,265,140,162,215,...,152,132,256,270,121,21,150,0,2016,AIAN
155,40131,"Rogers County, Oklahoma",3666,229,51,103,136,199,99,119,...,287,449,511,233,419,113,382,114,2016,AIAN
156,40143,"Tulsa County, Oklahoma",11811,1232,489,661,831,852,677,625,...,354,1265,1105,1222,768,538,464,342,2016,AIAN
157,40145,"Wagoner County, Oklahoma",2347,213,51,136,111,48,44,59,...,206,155,178,554,187,140,118,0,2016,AIAN
158,48201,"Harris County, Texas",4769,424,184,223,36,618,411,116,...,136,299,418,467,220,401,336,0,2016,AIAN
159,53009,"Clallam County, Washington",849,144,94,30,69,61,75,46,...,26,65,39,79,60,17,29,8,2016,AIAN
160,53033,"King County, Washington",4071,448,363,434,203,195,140,213,...,126,605,94,466,207,15,340,158,2016,AIAN
161,53073,"Whatcom County, Washington",1724,134,137,245,112,110,126,5,...,80,165,279,192,50,25,31,0,2016,AIAN
162,53077,"Yakima County, Washington",3010,334,111,366,138,422,126,78,...,240,103,208,412,144,137,74,31,2016,AIAN

In [11]:
# # Save Data to csv
census_AIAN_total_pd.to_csv("census_data/census_AIAN_total_cleaned_pd.csv")