In [1]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import time

In [2]:
# Import the census data into a pandas DataFrame
census_black_2000_pd = pd.read_csv("census_data/Black/DEC_00_SF3_P151B_with_ann.csv")

# Preview the data
#census_black_2000_pd.head()

In [3]:
census_black_2000_pd["Year"] = "2000"
census_black_2000_pd["Race"] = "Black"
census_black_2000_pd.head()

,Id,Id2,Geography,Estimate; Total:,Margin of Error; Total:,"Estimate; Total: - Less than $10,000","Margin of Error; Total: - Less than $10,000","Estimate; Total: - $10,000 to $14,999","Margin of Error; Total: - $10,000 to $14,999","Estimate; Total: - $15,000 to $19,999",...,"Estimate; Total: - $100,000 to $124,999","Margin of Error; Total: - $100,000 to $124,999","Estimate; Total: - $125,000 to $149,999","Margin of Error; Total: - $125,000 to $149,999","Estimate; Total: - $150,000 to $199,999","Margin of Error; Total: - $150,000 to $199,999","Estimate; Total: - $200,000 or more","Margin of Error; Total: - $200,000 or more",Year,Race
0,0500000US01001,1001,"Autauga County, Alabama",2566,NaN,617,NaN,268,NaN,271,...,35,NaN,6,NaN,0,NaN,27,NaN,2000,Black
1,0500000US01003,1003,"Baldwin County, Alabama",4650,NaN,940,NaN,599,NaN,551,...,67,NaN,43,NaN,20,NaN,35,NaN,2000,Black
2,0500000US01005,1005,"Barbour County, Alabama",4446,NaN,1553,NaN,555,NaN,425,...,31,NaN,10,NaN,0,NaN,28,NaN,2000,Black
3,0500000US01007,1007,"Bibb County, Alabama",1306,NaN,508,NaN,100,NaN,141,...,31,NaN,0,NaN,0,NaN,0,NaN,2000,Black
4,0500000US01009,1009,"Blount County, Alabama",146,NaN,46,NaN,2,NaN,15,...,0,NaN,0,NaN,0,NaN,0,NaN,2000,Black

In [4]:
# Import the census data into a pandas DataFrame
census_black_2005_pd = pd.read_csv("census_data/Black/ACS_05_EST_B19001B_with_ann.csv")

# Preview the data
census_black_2005_pd.head()

,Id,Id2,Geography,Estimate; Total:,Margin of Error; Total:,"Estimate; Total: - Less than $10,000","Margin of Error; Total: - Less than $10,000","Estimate; Total: - $10,000 to $14,999","Margin of Error; Total: - $10,000 to $14,999","Estimate; Total: - $15,000 to $19,999",...,"Estimate; Total: - $75,000 to $99,999","Margin of Error; Total: - $75,000 to $99,999","Estimate; Total: - $100,000 to $124,999","Margin of Error; Total: - $100,000 to $124,999","Estimate; Total: - $125,000 to $149,999","Margin of Error; Total: - $125,000 to $149,999","Estimate; Total: - $150,000 to $199,999","Margin of Error; Total: - $150,000 to $199,999","Estimate; Total: - $200,000 or more","Margin of Error; Total: - $200,000 or more"
0,0500000US01015,1015,"Calhoun County, Alabama",9092,876,2192,762,935,433,230,...,209,168,311,395,0,270,70,138,0,270
1,0500000US01055,1055,"Etowah County, Alabama",6030,636,1486,523,560,365,1054,...,280,224,0,270,0,270,0,270,0,270
2,0500000US01069,1069,"Houston County, Alabama",9421,510,2492,525,913,311,1050,...,420,174,264,201,0,270,10,18,31,50
3,0500000US01073,1073,"Jefferson County, Alabama",101964,2366,17190,2464,12829,2791,9510,...,6293,1526,2304,813,1589,711,1000,589,436,469
4,0500000US01081,1081,"Lee County, Alabama",10910,761,2591,677,974,438,712,...,794,388,88,95,32,40,28,50,65,79

In [5]:
census_black_2005_pd["Year"] = "2005"
census_black_2005_pd["Race"] = "Black"
census_black_2005_pd.head()

,Id,Id2,Geography,Estimate; Total:,Margin of Error; Total:,"Estimate; Total: - Less than $10,000","Margin of Error; Total: - Less than $10,000","Estimate; Total: - $10,000 to $14,999","Margin of Error; Total: - $10,000 to $14,999","Estimate; Total: - $15,000 to $19,999",...,"Estimate; Total: - $100,000 to $124,999","Margin of Error; Total: - $100,000 to $124,999","Estimate; Total: - $125,000 to $149,999","Margin of Error; Total: - $125,000 to $149,999","Estimate; Total: - $150,000 to $199,999","Margin of Error; Total: - $150,000 to $199,999","Estimate; Total: - $200,000 or more","Margin of Error; Total: - $200,000 or more",Year,Race
0,0500000US01015,1015,"Calhoun County, Alabama",9092,876,2192,762,935,433,230,...,311,395,0,270,70,138,0,270,2005,Black
1,0500000US01055,1055,"Etowah County, Alabama",6030,636,1486,523,560,365,1054,...,0,270,0,270,0,270,0,270,2005,Black
2,0500000US01069,1069,"Houston County, Alabama",9421,510,2492,525,913,311,1050,...,264,201,0,270,10,18,31,50,2005,Black
3,0500000US01073,1073,"Jefferson County, Alabama",101964,2366,17190,2464,12829,2791,9510,...,2304,813,1589,711,1000,589,436,469,2005,Black
4,0500000US01081,1081,"Lee County, Alabama",10910,761,2591,677,974,438,712,...,88,95,32,40,28,50,65,79,2005,Black

In [6]:
# Import the census data into a pandas DataFrame
census_black_2008_pd = pd.read_csv("census_data/Black/ACS_08_1YR_B19001B_with_ann.csv")

# Preview the data
census_black_2008_pd.head()

,Id,Id2,Geography,Estimate; Total:,Margin of Error; Total:,"Estimate; Total: - Less than $10,000","Margin of Error; Total: - Less than $10,000","Estimate; Total: - $10,000 to $14,999","Margin of Error; Total: - $10,000 to $14,999","Estimate; Total: - $15,000 to $19,999",...,"Estimate; Total: - $75,000 to $99,999","Margin of Error; Total: - $75,000 to $99,999","Estimate; Total: - $100,000 to $124,999","Margin of Error; Total: - $100,000 to $124,999","Estimate; Total: - $125,000 to $149,999","Margin of Error; Total: - $125,000 to $149,999","Estimate; Total: - $150,000 to $199,999","Margin of Error; Total: - $150,000 to $199,999","Estimate; Total: - $200,000 or more","Margin of Error; Total: - $200,000 or more"
0,0500000US01015,1015,"Calhoun County, Alabama",8730,1008,1681,601,1306,657,643,...,516,401,121,134,53,91,270,283,0,271
1,0500000US01055,1055,"Etowah County, Alabama",6483,807,1390,623,615,462,721,...,348,279,435,295,66,105,141,142,0,271
2,0500000US01069,1069,"Houston County, Alabama",8420,600,1430,392,881,268,841,...,389,158,137,96,107,97,12,20,62,67
3,0500000US01073,1073,"Jefferson County, Alabama",104361,2724,12700,1708,10169,1480,8637,...,8968,1687,4454,1121,1517,503,890,506,471,242
4,0500000US01081,1081,"Lee County, Alabama",11832,1150,1970,642,972,429,1607,...,765,354,172,133,152,188,12,20,0,271

In [7]:
census_black_2008_pd["Year"] = "2008"
census_black_2008_pd["Race"] = "Black"
census_black_2008_pd.head()

,Id,Id2,Geography,Estimate; Total:,Margin of Error; Total:,"Estimate; Total: - Less than $10,000","Margin of Error; Total: - Less than $10,000","Estimate; Total: - $10,000 to $14,999","Margin of Error; Total: - $10,000 to $14,999","Estimate; Total: - $15,000 to $19,999",...,"Estimate; Total: - $100,000 to $124,999","Margin of Error; Total: - $100,000 to $124,999","Estimate; Total: - $125,000 to $149,999","Margin of Error; Total: - $125,000 to $149,999","Estimate; Total: - $150,000 to $199,999","Margin of Error; Total: - $150,000 to $199,999","Estimate; Total: - $200,000 or more","Margin of Error; Total: - $200,000 or more",Year,Race
0,0500000US01015,1015,"Calhoun County, Alabama",8730,1008,1681,601,1306,657,643,...,121,134,53,91,270,283,0,271,2008,Black
1,0500000US01055,1055,"Etowah County, Alabama",6483,807,1390,623,615,462,721,...,435,295,66,105,141,142,0,271,2008,Black
2,0500000US01069,1069,"Houston County, Alabama",8420,600,1430,392,881,268,841,...,137,96,107,97,12,20,62,67,2008,Black
3,0500000US01073,1073,"Jefferson County, Alabama",104361,2724,12700,1708,10169,1480,8637,...,4454,1121,1517,503,890,506,471,242,2008,Black
4,0500000US01081,1081,"Lee County, Alabama",11832,1150,1970,642,972,429,1607,...,172,133,152,188,12,20,0,271,2008,Black

In [8]:
# Import the census data into a pandas DataFrame
census_black_2010_pd = pd.read_csv("census_data/Black/ACS_10_1YR_B19001B_with_ann.csv")

# Preview the data
census_black_2010_pd.head()

,Id,Id2,Geography,Estimate; Total:,Margin of Error; Total:,"Estimate; Total: - Less than $10,000","Margin of Error; Total: - Less than $10,000","Estimate; Total: - $10,000 to $14,999","Margin of Error; Total: - $10,000 to $14,999","Estimate; Total: - $15,000 to $19,999",...,"Estimate; Total: - $75,000 to $99,999","Margin of Error; Total: - $75,000 to $99,999","Estimate; Total: - $100,000 to $124,999","Margin of Error; Total: - $100,000 to $124,999","Estimate; Total: - $125,000 to $149,999","Margin of Error; Total: - $125,000 to $149,999","Estimate; Total: - $150,000 to $199,999","Margin of Error; Total: - $150,000 to $199,999","Estimate; Total: - $200,000 or more","Margin of Error; Total: - $200,000 or more"
0,0500000US01015,1015,"Calhoun County, Alabama",8308,1284,2399,761,1148,547,616,...,705,442,271,269,25,42,0,273,83,137
1,0500000US01055,1055,"Etowah County, Alabama",5363,641,483,300,992,370,496,...,90,125,85,104,44,72,0,273,0,273
2,0500000US01069,1069,"Houston County, Alabama",9911,508,2082,432,895,296,1438,...,412,183,128,101,113,119,21,36,29,35
3,0500000US01073,1073,"Jefferson County, Alabama",104711,2757,18537,2336,8963,1353,9630,...,5394,1047,4358,1141,1543,781,1023,484,635,405
4,0500000US01081,1081,"Lee County, Alabama",12559,819,2426,699,1672,654,581,...,903,436,361,256,232,175,0,273,17,29

In [9]:
census_black_2010_pd["Year"] = "2010"
census_black_2010_pd["Race"] = "Black"
census_black_2010_pd.head()

,Id,Id2,Geography,Estimate; Total:,Margin of Error; Total:,"Estimate; Total: - Less than $10,000","Margin of Error; Total: - Less than $10,000","Estimate; Total: - $10,000 to $14,999","Margin of Error; Total: - $10,000 to $14,999","Estimate; Total: - $15,000 to $19,999",...,"Estimate; Total: - $100,000 to $124,999","Margin of Error; Total: - $100,000 to $124,999","Estimate; Total: - $125,000 to $149,999","Margin of Error; Total: - $125,000 to $149,999","Estimate; Total: - $150,000 to $199,999","Margin of Error; Total: - $150,000 to $199,999","Estimate; Total: - $200,000 or more","Margin of Error; Total: - $200,000 or more",Year,Race
0,0500000US01015,1015,"Calhoun County, Alabama",8308,1284,2399,761,1148,547,616,...,271,269,25,42,0,273,83,137,2010,Black
1,0500000US01055,1055,"Etowah County, Alabama",5363,641,483,300,992,370,496,...,85,104,44,72,0,273,0,273,2010,Black
2,0500000US01069,1069,"Houston County, Alabama",9911,508,2082,432,895,296,1438,...,128,101,113,119,21,36,29,35,2010,Black
3,0500000US01073,1073,"Jefferson County, Alabama",104711,2757,18537,2336,8963,1353,9630,...,4358,1141,1543,781,1023,484,635,405,2010,Black
4,0500000US01081,1081,"Lee County, Alabama",12559,819,2426,699,1672,654,581,...,361,256,232,175,0,273,17,29,2010,Black

In [10]:
# Import the census data into a pandas DataFrame
census_black_2013_pd = pd.read_csv("census_data/Black/ACS_13_1YR_B19001B_with_ann.csv")
census_black_2013_pd["Year"] = "2013"
census_black_2013_pd["Race"] = "Black"
census_black_2013_pd.head()

,Id,Id2,Geography,Estimate; Total:,Margin of Error; Total:,"Estimate; Total: - Less than $10,000","Margin of Error; Total: - Less than $10,000","Estimate; Total: - $10,000 to $14,999","Margin of Error; Total: - $10,000 to $14,999","Estimate; Total: - $15,000 to $19,999",...,"Estimate; Total: - $100,000 to $124,999","Margin of Error; Total: - $100,000 to $124,999","Estimate; Total: - $125,000 to $149,999","Margin of Error; Total: - $125,000 to $149,999","Estimate; Total: - $150,000 to $199,999","Margin of Error; Total: - $150,000 to $199,999","Estimate; Total: - $200,000 or more","Margin of Error; Total: - $200,000 or more",Year,Race
0,0500000US01015,1015,"Calhoun County, Alabama",9027,958,1889,772,485,239,1106,...,53,67,76,119,0,192,0,192,2013,Black
1,0500000US01051,1051,"Elmore County, Alabama",5133,907,741,505,585,505,90,...,327,365,159,216,0,192,0,192,2013,Black
2,0500000US01055,1055,"Etowah County, Alabama",6707,676,902,471,781,458,812,...,260,255,0,192,0,192,0,192,2013,Black
3,0500000US01069,1069,"Houston County, Alabama",9872,504,1997,321,1175,268,966,...,162,88,208,122,64,60,34,34,2013,Black
4,0500000US01073,1073,"Jefferson County, Alabama",105789,2964,17624,2123,9904,1418,8169,...,5012,1164,1906,631,1144,500,562,327,2013,Black

In [28]:
# Import the census data into a pandas DataFrame
census_black_2016_pd = pd.read_csv("census_data/Black/ACS_16_1YR_B19001B_with_ann.csv")
census_black_2016_pd.head()
census_black_2016_pd["Year"] = "2016"
census_black_2016_pd["Race"] = "Black"
census_black_2016_pd.head()

,Id,Id2,Geography,Estimate; Total:,Margin of Error; Total:,"Estimate; Total: - Less than $10,000","Margin of Error; Total: - Less than $10,000","Estimate; Total: - $10,000 to $14,999","Margin of Error; Total: - $10,000 to $14,999","Estimate; Total: - $15,000 to $19,999",...,"Estimate; Total: - $100,000 to $124,999","Margin of Error; Total: - $100,000 to $124,999","Estimate; Total: - $125,000 to $149,999","Margin of Error; Total: - $125,000 to $149,999","Estimate; Total: - $150,000 to $199,999","Margin of Error; Total: - $150,000 to $199,999","Estimate; Total: - $200,000 or more","Margin of Error; Total: - $200,000 or more",Year,Race
0,0500000US01015,1015,"Calhoun County, Alabama",8912,889,953,421,1105,609,1335,...,481,387,87,131,152,130,48,74,2016,Black
1,0500000US01055,1055,"Etowah County, Alabama",6146,763,1298,553,717,512,588,...,0,195,122,159,0,195,43,69,2016,Black
2,0500000US01069,1069,"Houston County, Alabama",10353,657,1725,351,1214,297,1034,...,239,155,198,155,188,116,29,29,2016,Black
3,0500000US01073,1073,"Jefferson County, Alabama",109168,3317,15187,1854,8485,1545,8415,...,5509,1157,2711,812,2196,706,907,468,2016,Black
4,0500000US01081,1081,"Lee County, Alabama",14654,1218,1893,814,644,449,825,...,1200,773,88,148,234,333,43,74,2016,Black

In [29]:
# Concatenate dataframes]
census_black_total_pd = pd.concat([census_black_2000_pd, census_black_2005_pd,census_black_2008_pd, census_black_2010_pd, census_black_2013_pd, census_black_2016_pd], ignore_index=True)
census_black_total_pd.head()

,Id,Id2,Geography,Estimate; Total:,Margin of Error; Total:,"Estimate; Total: - Less than $10,000","Margin of Error; Total: - Less than $10,000","Estimate; Total: - $10,000 to $14,999","Margin of Error; Total: - $10,000 to $14,999","Estimate; Total: - $15,000 to $19,999",...,"Estimate; Total: - $100,000 to $124,999","Margin of Error; Total: - $100,000 to $124,999","Estimate; Total: - $125,000 to $149,999","Margin of Error; Total: - $125,000 to $149,999","Estimate; Total: - $150,000 to $199,999","Margin of Error; Total: - $150,000 to $199,999","Estimate; Total: - $200,000 or more","Margin of Error; Total: - $200,000 or more",Year,Race
0,0500000US01001,1001,"Autauga County, Alabama",2566,NaN,617,NaN,268,NaN,271,...,35,NaN,6,NaN,0,NaN,27,NaN,2000,Black
1,0500000US01003,1003,"Baldwin County, Alabama",4650,NaN,940,NaN,599,NaN,551,...,67,NaN,43,NaN,20,NaN,35,NaN,2000,Black
2,0500000US01005,1005,"Barbour County, Alabama",4446,NaN,1553,NaN,555,NaN,425,...,31,NaN,10,NaN,0,NaN,28,NaN,2000,Black
3,0500000US01007,1007,"Bibb County, Alabama",1306,NaN,508,NaN,100,NaN,141,...,31,NaN,0,NaN,0,NaN,0,NaN,2000,Black
4,0500000US01009,1009,"Blount County, Alabama",146,NaN,46,NaN,2,NaN,15,...,0,NaN,0,NaN,0,NaN,0,NaN,2000,Black

In [30]:
# Save Data to csv
census_black_total_pd.to_csv("census_data/census_black_total_pd.csv")